version: '3.7'
x-var: &IRIS_IMAGE
  "containers.intersystems.com/intersystems/iris:2022.1.0.209.0"
x-var: &ARBITER_IMAGE
  "containers.intersystems.com/intersystems/arbiter:2022.1.0.209.0"
x-var: &WEBGW_IMAGE
  "iris-webgateway-example_web:latest"

services:
  ap1a:
    container_name: ap1a
    hostname: ap1a
    image: *IRIS_IMAGE
    init: true    
    volumes:
      #- ./iris1A:/DB
      #- ./iris1A:/ISC
      - ./:/ISC/utiles
      - ./cpf:/cpf
      - ./project:/project
      - ./uploadA:/home/irisowner/upload
    environment:
      #- ISC_DATA_DIRECTORY=/ISC/install
      - ISC_CPF_MERGE_FILE=/cpf/merge.cpf
      - IRIS_systemname=AP1A/IRIS
      - ARBITER_ip=10.0.100.10
      - MirrorAddress_ip=10.0.1.2
      - MIRRORROLE=PRIMARY
      - ECPAddress_ip=10.0.100.2
      - CSPConfigName=ap1,ap1a
      - TZ=JST-9
    ports:
      - "9092:52773"
    command:
      --key /ISC/utiles/iris.key
      -a /ISC/utiles/installer.sh
      --check-caps false

    networks:
      iris-tier:
        ipv4_address: 10.0.1.2
      arbiter-tier:
        ipv4_address: 10.0.100.2

  ap1b:
    container_name: ap1b
    hostname: ap1b
    image: *IRIS_IMAGE
    init: true    
    depends_on:
      - ap1a
    volumes:
      #- ./iris1B:/DB
      #- ./iris1B:/ISC
      - ./:/ISC/utiles
      - ./cpf:/cpf
      - ./project:/project
      - ./uploadB:/home/irisowner/upload
    environment:
      #- ISC_DATA_DIRECTORY=/ISC/install
      - ISC_CPF_MERGE_FILE=/cpf/merge.cpf
      - IRIS_systemname=AP1B/IRIS
      - primaryAgentAddress_ip=10.0.1.2
      - MirrorAddress_ip=10.0.1.3
      - MIRRORROLE=BACKUP
      - ECPAddress_ip=10.0.100.3
      - CSPConfigName=ap1,ap1b
      - TZ=JST-9
    ports:
      - "9093:52773"
    command:
      --key /ISC/utiles/iris.key
      -a /ISC/utiles/installer.sh
      --check-caps false
    networks:
      iris-tier:
        ipv4_address: 10.0.1.3
      arbiter-tier:
        ipv4_address: 10.0.100.3    

  ap1d:
    container_name: ap1d
    hostname: ap1d
    image: *IRIS_IMAGE
    init: true    
    depends_on:
      - ap1a
    volumes:
      #- ./iris1B:/DB
      #- ./iris1B:/ISC
      - ./:/ISC/utiles
      - ./cpf:/cpf
      - ./project:/project
      - ./uploadB:/home/irisowner/upload
    environment:
      #- ISC_DATA_DIRECTORY=/ISC/install
      - ISC_CPF_MERGE_FILE=/cpf/merge.cpf
      - IRIS_systemname=AP1D/IRIS
      - primaryAgentAddress_ip=10.0.1.2
      - MirrorAddress_ip=10.0.1.4
      - MIRRORROLE=DR
      - ECPAddress_ip=10.0.100.4
      - CSPConfigName=ap1,ap1d
      - TZ=JST-9
    ports:
      - "9094:52773"
    command:
      --key /ISC/utiles/iris.key
      -a /ISC/utiles/installer.sh
      --check-caps false
    networks:
      iris-tier:
        ipv4_address: 10.0.1.4
      arbiter-tier:
        ipv4_address: 10.0.100.4

  ap2a:
    container_name: ap2a
    hostname: ap2a
    image: *IRIS_IMAGE
    init: true    
    volumes:
      #- ./iris2A:/DB
      #- ./iris2A:/ISC
      - ./:/ISC/utiles
      - ./cpf:/cpf
      - ./project:/project
      - ./uploadA:/home/irisowner/upload
    environment:
      #- ISC_DATA_DIRECTORY=/ISC/install
      - ISC_CPF_MERGE_FILE=/cpf/merge.cpf
      - IRIS_systemname=AP2A/IRIS
      - ARBITER_ip=10.0.100.10
      - MirrorAddress_ip=10.0.1.5
      - ECPAddress_ip=10.0.100.5
      - MIRRORROLE=PRIMARY
      - CSPConfigName=ap2,ap2a
      - TZ=JST-9
    ports:
      - "9095:52773"
    command:
      --key /ISC/utiles/iris.key
      -a /ISC/utiles/installer.sh
      --check-caps false
    networks:
      iris-tier:
        ipv4_address: 10.0.1.5
      arbiter-tier:
        ipv4_address: 10.0.100.5

  ap2b:
    container_name: ap2b
    hostname: ap2b
    image: *IRIS_IMAGE
    init: true    
    depends_on:
      - ap2a
    volumes:
      #- ./iris2B:/DB
      #- ./iris2B:/ISC
      - ./:/ISC/utiles
      - ./cpf:/cpf
      - ./project:/project
      - ./uploadB:/home/irisowner/upload
    environment:
      #- ISC_DATA_DIRECTORY=/ISC/install
      - ISC_CPF_MERGE_FILE=/cpf/merge.cpf
      - IRIS_systemname=AP2B/IRIS
      - primaryAgentAddress_ip=10.0.1.5
      - MirrorAddress_ip=10.0.1.6
      - ECPAddress_ip=10.0.100.6
      - MIRRORROLE=BACKUP
      - CSPConfigName=ap2,ap2b
      - TZ=JST-9
    ports:
      - "9096:52773"
    command:
      --key /ISC/utiles/iris.key
      -a /ISC/utiles/installer.sh
      --check-caps false
    networks:
      iris-tier:
        ipv4_address: 10.0.1.6
      arbiter-tier:
        ipv4_address: 10.0.100.6

  # mirror reporting member
  ap2r:
    container_name: ap2r
    hostname: ap2r
    image: *IRIS_IMAGE
    init: true    
    depends_on:
      - ap2a
    volumes:
      #- ./iris2R:/DB
      #- ./iris2R:/ISC
      - ./:/ISC/utiles
      - ./cpf:/cpf
      - ./project:/project
      - ./uploadB:/home/irisowner/upload
    environment:
      #- ISC_DATA_DIRECTORY=/ISC/install
      - ISC_CPF_MERGE_FILE=/cpf/merge.cpf
      - IRIS_systemname=ap2r/IRIS
      - primaryAgentAddress_ip=10.0.1.5
      - MirrorAddress_ip=10.0.1.7
      - ECPAddress_ip=10.0.100.7
      - MIRRORROLE=REPORTRW
      - CSPConfigName=ap2,ap2r
      - TZ=JST-9
    ports:
      - "9097:52773"
    command:
      --key /ISC/utiles/iris.key
      -a /ISC/utiles/installer.sh
      --check-caps false
    networks:
      iris-tier:
        ipv4_address: 10.0.1.7
      arbiter-tier:
        ipv4_address: 10.0.100.7

  arbiter:
    container_name: arbiter
    hostname: arbiter
    image: *ARBITER_IMAGE
    init: true    
    command: 
      - /usr/local/etc/irissys/startISCAgent.sh 2188
    environment:
      - TZ=JST-9
    networks:
      arbiter-tier:
        ipv4_address: 10.0.100.10

  webgw1:
    container_name: webgw
    hostname: webgw
    image: *WEBGW_IMAGE
    init: true    
    environment:
      - TZ=JST-9
      - CONFIG_NAME=ap1a
      - SERVER_HOST=10.0.100.2
      - SERVER_PORT=1972
      - CONFIG_NAME2=ap1b
      - SERVER_HOST2=10.0.100.3
      - SERVER_PORT2=1972
      - CONFIG_NAME3=ap1d
      - SERVER_HOST3=10.0.100.4
      - SERVER_PORT3=1972
      - CONFIG_NAME4=ap2a
      - SERVER_HOST4=10.0.100.5
      - SERVER_PORT4=1972
      - CONFIG_NAME5=ap2b
      - SERVER_HOST5=10.0.100.6
      - SERVER_PORT5=1972
      - CONFIG_NAME6=ap2r
      - SERVER_HOST6=10.0.100.7
      - SERVER_PORT6=1972
      - MIRROR_CONFIG_NAME=ap1
      - MIRROR_CONFIG_NAME2=ap2
    ports:
      - "8080:80"
    networks:
      arbiter-tier:
        ipv4_address: 10.0.100.11

  webgw2:
    container_name: webgw2
    hostname: webgw2
    image: *WEBGW_IMAGE
    init: true    
    environment:
      - TZ=JST-9
      - CONFIG_NAME=ap1a
      - SERVER_HOST=10.0.100.2
      - SERVER_PORT=1972
      - CONFIG_NAME2=ap1b
      - SERVER_HOST2=10.0.100.3
      - SERVER_PORT2=1972
      - CONFIG_NAME3=ap1d
      - SERVER_HOST3=10.0.100.4
      - SERVER_PORT3=1972
      - CONFIG_NAME4=ap2a
      - SERVER_HOST4=10.0.100.5
      - SERVER_PORT4=1972
      - CONFIG_NAME5=ap2b
      - SERVER_HOST5=10.0.100.6
      - SERVER_PORT5=1972
      - CONFIG_NAME6=ap2r
      - SERVER_HOST6=10.0.100.7
      - SERVER_PORT6=1972
      - MIRROR_CONFIG_NAME=ap1
      - MIRROR_CONFIG_NAME2=ap2
    ports:
      - "8081:80"
    networks:
      arbiter-tier:
        ipv4_address: 10.0.100.12

  nginx:
    hostname: nginx
    container_name: nginx
    image: nginx
    init: true
    depends_on:
      - webgw1
      - webgw2
    environment:
      - TZ=JST-9
    volumes:
    - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      arbiter-tier:
        ipv4_address: 10.0.100.13

  haproxy:
    # need to build this image to add curl for external check
    build:
      context: ./haproxy
    hostname: haproxy
    container_name: haproxy
    init: true
    environment:
      - TZ=JST-9
    volumes:
    - ./haproxy-conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    - ./haproxy-conf/check.sh:/usr/local/etc/haproxy/check.sh
    ports:
      - "1972:1972"
      - "11972:11972"
    networks:
      iris-tier:
        ipv4_address: 10.0.1.8

networks:
  iris-tier:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
  iris-dr-tier:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.2.0/24
  arbiter-tier:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.100.0/24