version: '3.7'
x-var: &IRIS_IMAGE
  "containers.intersystems.com/intersystems/iris:2020.3.0.221.0"
x-var: &ARBITER_IMAGE
  "containers.intersystems.com/intersystems/arbiter:2020.3.0.221.0"
x-var: &WEBGW_IMAGE
  "iris-webgateway-example_web:latest"

services:
  mirrorA:
    container_name: mirrorA
    hostname: mirrorA
    image: *IRIS_IMAGE
    init: true    
    depends_on:
      - arbiter
    volumes:
      - ./irisA:/ISC
      - ./:/ISC/utiles
      - ./cpf:/cpf
      - ./project:/project
      - ./uploadA:/home/irisowner/upload
    environment:
      - ISC_DATA_DIRECTORY=/ISC/install
      - ISC_CPF_MERGE_FILE=/cpf/merge.cpf
      - IRIS_systemname=mirrorA
      - ARBITER_ip=10.1.100.10
      - MirrorAddress_ip=10.1.1.2
      - ECPAddress_ip=10.1.1.2
      - TZ=JST-9
    ports:
      - "9092:52773"
    command:
      --key /ISC/utiles/iris.key
      -a /ISC/utiles/installer.sh
    networks:
      iris-tier:
        ipv4_address: 10.1.1.2    

  mirrorB:
    container_name: mirrorB
    hostname: mirrorB
    image: *IRIS_IMAGE
    init: true    
    depends_on:
      - mirrorA
      - arbiter
    volumes:
      - ./irisB:/ISC
      - ./:/ISC/utiles
      - ./cpf:/cpf
      - ./project:/project
      - ./uploadB:/home/irisowner/upload
    environment:
      - ISC_DATA_DIRECTORY=/ISC/install
      - ISC_CPF_MERGE_FILE=/cpf/merge.cpf
      - IRIS_systemname=mirrorB
      - primaryAgentAddress_ip=10.1.1.2
      - MirrorAddress_ip=10.1.1.3
      - ECPAddress_ip=10.1.1.3
      - TZ=JST-9
    ports:
      - "9093:52773"
    command:
      --key /ISC/utiles/iris.key
      -a /ISC/utiles/installer.sh
    networks:
      iris-tier:
        ipv4_address: 10.1.1.3    

  arbiter:
    container_name: arbiter
    hostname: arbiter
    image: *ARBITER_IMAGE
    init: true    
    command: 
      - /usr/local/etc/irissys/startISCAgent.sh 2188
    environment:
      - TZ=JST-9
    networks:
      iris-tier:
        ipv4_address: 10.1.100.10

  webgw1:
    container_name: webgw1
    hostname: webgw1
    image: *WEBGW_IMAGE
    init: true    
    depends_on:
      - mirrorA
      - mirrorB
    environment:
      - TZ=JST-9
      - CONFIG_NAME=MIRRORA
      - SERVER_HOST=mirrorA
      - SERVER_PORT=1972
      - CONFIG_NAME2=MIRRORB
      - SERVER_HOST2=mirrorB
      - SERVER_PORT2=1972
    ports:
      - "8080:80"
    networks:
      iris-tier:
        ipv4_address: 10.1.100.11

  webgw2:
    container_name: webgw2
    hostname: webgw2
    image: *WEBGW_IMAGE
    init: true    
    depends_on:
      - mirrorA
      - mirrorB
    environment:
      - TZ=JST-9
      - CONFIG_NAME=MIRRORA
      - SERVER_HOST=mirrorA
      - SERVER_PORT=1972
      - CONFIG_NAME2=MIRRORB
      - SERVER_HOST2=mirrorB
      - SERVER_PORT2=1972
    ports:
      - "8081:80"
    networks:
      iris-tier:
        ipv4_address: 10.1.100.12
  nginx:
    hostname: nginx
    container_name: nginx
    image: nginx
    init: true
    depends_on:
      - webgw1
      - webgw2
    environment:
      - TZ=JST-9
    volumes:
    - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      iris-tier:
        ipv4_address: 10.1.100.13

networks:
  iris-tier:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.0.0/16
