version: '3.7'
## docker login docker.iscinternal.com
## Connect to SMP mirror A
## http://127.0.0.1:9092/csp/sys/UtilHome.csp
## Commands: 
# docker exec -it mirrorA iris session IRIS

x-var: &IRIS_IMAGE
  "intersystems/iris:2020.1.0.215.0"
x-var: &ARBITER_IMAGE
  "intersystems/arbiter:2020.1.0.215.0"

services:
  mirrorA:
    container_name: mirrorA
    hostname: mirrorA
    image: *IRIS_IMAGE
    init: true    
    depends_on:
      - arbiter
    volumes:
      - ./irisA:/ISC
      - ./:/ISC/utiles
    environment:
      - ISC_DATA_DIRECTORY=/ISC/install
      - IRIS_hostname=mirrorA
      - ARBITER_hostname=arbiter
    ports:
      - "9092:52773"
    command:
      --key /ISC/utiles/iris.key
      -a /ISC/utiles/installer.sh
    
  mirrorB:
    container_name: mirrorB
    hostname: mirrorB
    image: *IRIS_IMAGE
    init: true    
    depends_on:
      - mirrorA
      - arbiter
    volumes:
      - ./irisB:/ISC
      - ./:/ISC/utiles
    environment:
      - ISC_DATA_DIRECTORY=/ISC/install
      - IRIS_hostname=mirrorB
    ports:
      - "9093:52773"
    command:
      --key /ISC/utiles/iris.key
      -a /ISC/utiles/installer.sh

  arbiter:
    container_name: arbiter
    hostname: arbiter
    image: *ARBITER_IMAGE
    init: true    
    command: 
      - /usr/local/etc/irissys/startISCAgent.sh 2188
